apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    route:
      receiver: 'pager'
      group_wait: 10s
      group_interval: 10m
      repeat_interval: 1h

    receivers:
    - name: 'pager'
      # Email example (uncomment & configure)
      email_configs:
      - to: 'oncall@example.com'
        send_resolved: true

    # Slack example (requires webhook)
    # - name: 'slack'
    #   slack_configs:
    #   - api_url: 'https://hooks.slack.com/services/XXX/YYY/ZZZ'
    #     channel: '#alerts'
